import React from 'react';
import Link from 'next/link';
import { Metadata } from 'next';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'AGB | Nextmove Digital GmbH | Vertragsbedingungen',
  description: 'Allgemeine Geschäftsbedingungen der Nextmove Digital GmbH. Erfahren Sie mehr über unsere Vertragsbedingungen und Leistungen im Bereich Agenturdienstleistungen.',
  alternates: {
    canonical: '/agb',
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function AGB() {
  return (
    <main className="flex min-h-screen flex-col bg-black">
      <Header />
      <div className="container mx-auto px-4 pt-36 pb-20 flex-grow">
        <div className="max-w-4xl mx-auto bg-black/50 p-8 rounded-xl border border-white/10">
          <h1 className="text-3xl font-bold text-white mb-8">Allgemeine Geschäftsbedingungen</h1>

          <div className="space-y-6 text-gray-300 leading-relaxed">
            <div className="mb-8">
              <p className="font-semibold text-white mb-4">von</p>
              <p className="font-semibold text-white mb-2">Nextmove Digital GmbH<br />
              i. Gr<br />
              Papenstraße 23<br />
              22089 Hamburg</p>
              <p className="mb-6">- im Folgenden: Auftragnehmer -</p>
            </div>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Teil 1 – Allgemeine Bestimmungen</h2>

              <h3 className="text-xl font-semibold text-white mb-3">1.1 Allgemeines</h3>
              <p className="mb-4">1.1.1 Der Auftragnehmer bietet dem Kunden verschiedene Agenturleistungen an. Der spezifische Leistungsumfang ist Gegenstand von Individualvereinbarungen zwischen dem Auftragnehmer und dem Kunden.</p>
              <p className="mb-4">1.1.2 Der Auftragnehmer schließt keine Verträge mit Verbrauchern bzw. Privatpersonen.</p>
              <p className="mb-4">1.1.3 Der Auftragnehmer ist berechtigt, in eigenem Namen und auf eigene Rechnung die erforderlichen Leistungen an Subunternehmer zu vergeben, die ihrerseits ebenfalls Subunternehmer einsetzen dürfen. Der Auftragnehmer bleibt hierbei vorbehaltlich abweichender Vereinbarungen alleiniger Vertragspartner des Kunden. Der Einsatz von Subunternehmern erfolgt nicht, sofern für den Auftragnehmer ersichtlich ist, dass deren Einsatz berechtigten Interessen des Kunden zuwiderläuft.</p>
              <p className="mb-4">1.1.4 Soweit neben diesen AGB weitere Vertragsdokumente in Text- oder Schriftform Vertragsbestandteil geworden sind, gehen die Regelungen dieser weiteren Vertragsdokumente im Widerspruchsfalle den vorliegenden AGB vor.</p>
              <p className="mb-6">1.1.5 Von diesen Geschäftsbedingungen abweichende AGB, die durch den Kunden verwendet werden, erkennt der Auftragnehmer – vorbehaltlich einer ausdrücklichen Zustimmung – nicht an.</p>

              <h3 className="text-xl font-semibold text-white mb-3">1.2 Mitwirkungspflichten des Kunden</h3>
              <p className="mb-4">1.2.1 Sofern der Kunde dem Auftragnehmer Texte, Bilder oder sonstige Inhalte zur Erf&uuml;llung der in Auftrag gegeben Leistungen zur Verf&uuml;gung stellt, hat er daf&uuml;r zu sorgen, dass diese Inhalte nicht gegen die Rechte Dritter (z.&nbsp;B. Urheberrechte, Markenrecht etc.) oder sonstige Rechtsnormen verstoßen. Es wird in diesem Zusammenhang darauf hingewiesen, dass der Auftragnehmer von Rechts wegen nicht berechtigt ist, Rechtsberatungsleistungen gegen&uuml;ber dem Kunden zu erbringen. Der Auftragnehmer ist vor allem nicht verpflichtet und rechtlich nicht in der Lage, das Gesch&auml;ftsmodell des Kunden und/oder die vom Kunden selbst erstellten oder erworbenen Werke (Layouts, Grafiken, Texte etc.) auf ihre Vereinbarkeit mit dem geltenden Recht zu pr&uuml;fen. Der Auftragnehmer wird insbesondere keine Markenrecherchen oder sonstige Schutzrechtskollisionspr&uuml;fungen in Bezug auf die vom Kunden zur Verf&uuml;gung gestellten Werke vornehmen. Soweit der Kunde bestimmte Weisungen bzgl. des herzustellenden Werks erteilt, haftet er hierf&uuml;r selbst.</p>
              <p className="mb-4">1.2.2 Der Kunde ist verpflichtet, die von ihm zum Zwecke der Auftragserf&uuml;llung zur Verf&uuml;gung zu stellenden Informationen, Daten, Werke (z.&nbsp;B. die Daten f&uuml;r das Impressum, Grafiken, Logos etc.) und Zug&auml;nge vollst&auml;ndig und korrekt mitzuteilen. Er hat ferner daf&uuml;r Sorge zu tragen, dass die von ihm erteilten Weisungen mit dem geltenden Recht in Einklang stehen.</p>
              <p className="mb-4">1.2.3 Der Kunde ist – vorbehaltlich abweichender Individualvereinbarungen – f&uuml;r die Beschaffung des Materials zur Erbringung der Agenturleistungen (z.&nbsp;B. Grafiken, Videos) selbst verantwortlich und stellt diese dem Auftragnehmer rechtzeitig zur Verf&uuml;gung. Stellt der Kunde diese nicht zur Verf&uuml;gung und macht er auch keine weitergehenden Vorgaben, so kann der Auftragnehmer nach eigener Wahl unter Beachtung der urheberrechtlichen Kennzeichnungsvorgaben Bildmaterial g&auml;ngiger Anbieter (z.&nbsp;B. Stockfoto-Dienstleister) verwenden oder die entsprechenden Teile der Webseite mit einem Platzhalter versehen.</p>
              <p className="mb-4">1.2.4 Sofern f&uuml;r einzelne Auftragsbestandteile der Abschluss eines Auftragsverarbeitungsvertrags nach Art. 28 DSGVO erforderlich ist, verpflichten sich beide Vertragsparteien, einen solchen – vom Auftragnehmer zu stellenden – Vertrag vor Beginn der Leistungserbringung abzuschließen.</p>
              <p className="mb-4">1.2.5 F&uuml;r Verz&ouml;gerungen und Versp&auml;tungen bei der Umsetzung von Projekten, die durch eine versp&auml;tete (notwendige) Mit- bzw. Zuarbeit des Kunden entstehen, ist der Auftragnehmer gegen&uuml;ber dem Kunden in keinerlei Hinsicht verantwortlich; die Vorschriften unter der &Uuml;berschrift „Haftung/Freistellung" bleiben hiervon unber&uuml;hrt.</p>
              <p className="mb-6">1.2.6 Kommt der Kunde seinen Mitwirkungspflichten aus dieser Ziffer nicht nach, kann der Auftragnehmer dem Kunden den hierdurch entstehenden Zusatzaufwand (z.&nbsp;B. Kosten f&uuml;r Stockfotos und Zeitaufwand f&uuml;r deren Suche) in Rechnung stellen.</p>

              <h3 className="text-xl font-semibold text-white mb-3">1.3 Einsatz von K&uuml;nstlicher Intelligenz (KI)</h3>
              <p className="mb-4">1.3.1 Der Auftragnehmer ist berechtigt, im Rahmen der Leistungserbringung Technologien der K&uuml;nstlichen Intelligenz (KI-Tools) zur Erstellung von Inhalten (z.&nbsp;B. Text, Bild, Ton oder Video) einzusetzen. Sofern nicht anders vereinbart, werden alle von einer KI generierten Inhalte nach deren Erstellung von einer nat&uuml;rlichen Person gepr&uuml;ft und bei Bedarf angepasst. Der Einsatz von KI-Tools erfolgt nicht, sofern f&uuml;r den Auftragnehmer ersichtlich ist, dass deren Einsatz berechtigten Interessen des Kunden zuwiderl&auml;uft. Will der Kunde, dass KI-Technologien f&uuml;r bestimmte Projekte oder Teile davon nicht eingesetzt werden, so hat er dies dem Auftragnehmer in Textform eigenst&auml;ndig mitzuteilen.</p>
              <p className="mb-4">1.3.2 Der Auftragnehmer sichert zu, dass Inhalte, die ganz oder teilweise mit KI erstellt wurden, nicht die Rechte von Dritten verletzen. Sofern an Inhalten, die ganz oder teilweise mit Hilfe von KI erstellt wurden, ausschlie&szlig;liche Nutzungsrechte &uuml;bertragen werden sollen, wird der Auftragnehmer daf&uuml;r Sorge tragen, dass eine solche Nutzungsrechte&uuml;bertragung m&ouml;glich ist (z.&nbsp;B. indem die KI-generierten Werke so abgewandelt werden, dass Sch&ouml;pfungsh&ouml;he und damit Urheberrechtschutz erreicht wird).</p>
              <p className="mb-6">1.3.3 Eine separate Kennzeichnung von KI-generierten Inhalten ist nur geschuldet, wenn und soweit die Kennzeichnung des Inhaltes gesetzlich vorgeschrieben ist oder sofern bereits zum Zeitpunkt der Leistungserbringung absehbar ist, dass eine Kennzeichnungspflicht in absehbarer Zeit gesetzlich vorgeschrieben sein wird (z.&nbsp;B. aufgrund von Regelungen in der KI-Verordnung). Gleiches gilt f&uuml;r Mitteilungen dar&uuml;ber, dass bestimmte Arbeitsergebnisse unter Zuhilfenahme k&uuml;nstlicher Intelligenz erstellt worden.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Teil 2 – Onlineauftritte und Technik</h2>

              <h3 className="text-xl font-semibold text-white mb-3">2.1 Webseiten- und Shoperstellung (agil)</h3>
              <p className="mb-4">2.1.1 Sofern keine abweichenden Individualvereinbarungen getroffen wurden, erfolgt die Erstellung von neuen oder die Erweiterung bestehender Webseiten/Shops oder Web-/Shopkomponenten (nachfolgend „Webseitenerstellung") auf Grundlage agiler Methoden. Die &uuml;brigen Regelungen dieser AGB bleiben unber&uuml;hrt.</p>
              <p className="mb-4">2.1.2 Gegenstand von Webseiten-Erstellungsvertr&auml;gen zwischen dem Auftragnehmer und dem Kunden ist grunds&auml;tzlich die Entwicklung neuer Webseiten oder die Erweiterung bestehender Webseiten (z.&nbsp;B. Einbinden neuer Schnittstellen oder Programmierung neuer Online-Anwendungen) unter Beachtung der technischen und/oder gestalterischen Vorgaben des Kunden. Zwischen den Parteien geschlossene Webseiten-Erstellungsvertr&auml;ge sind Werkvertr&auml;ge im Sinne von §&sect; 631 ff. BGB.</p>
              <p className="mb-4">2.1.3 Die im Einzelnen vereinbarten Leistungen ergeben sich aus dem zwischen dem Auftragnehmer und dem Kunden individuell abgeschlossenen Vertrag. Hierzu stellt der Kunde beim Auftragnehmer zun&auml;chst eine Anfrage mit einer m&ouml;glichst genauen Beschreibung der von ihm gew&uuml;nschten Webseiten-Inhalte (gestalterische Inhalte wie Bilder, Layouts, Logos, Schriften u. &Auml;. sind vorbehaltlich abweichender Vereinbarungen vom Kunden festzulegen und zur Verf&uuml;gung zu stellen). Diese Anfrage stellt eine Aufforderung zur Abgabe eines Angebots durch den Auftragnehmer dar. Der Auftragnehmer wird die in der Anfrage beschriebenen Vorstellungen des Kunden nach bestem Wissen und Gewissen auf Vollst&auml;ndigkeit, Eignung (mit Ausnahme der rechtlichen Eignung, insbesondere hinsichtlich der Rechte von Dritten), Eindeutigkeit, Realisierbarkeit und Widerspruchsfreiheit pr&uuml;fen und auf Grundlage der aus der Kundenanfrage hervorgehenden W&uuml;nsche ein Angebot erstellen. Erst durch die Annahme des Angebots durch den Kunden kommt ein Vertrag zwischen dem Auftragnehmer und dem Kunden zustande.</p>
              <p className="mb-4">2.1.4 Der Kunde kann jederzeit Kundenw&uuml;nsche einbringen, soweit diese durch den urspr&uuml;nglich vereinbarten Leistungsumfang gedeckt sind. Derartige Anpassungen werden Bestandteil des urspr&uuml;nglichen Vertrags, wenn beide Vertragsparteien in Textform (z.&nbsp;B. per E-Mail) zustimmen. Im &Uuml;brigen ist der Auftragnehmer nur zur Herstellung der im Vertrag aufgelisteten Funktionen/Positionen bzw. zur Erbringung der vereinbarten Dienstleistung verpflichtet. Dar&uuml;berhinausgehende Leistungen m&uuml;ssen gesondert vereinbart und verg&uuml;tet werden.</p>
              <p className="mb-4">2.1.5 Sobald die Webseite fertiggestellt wurde, wird der Auftragnehmer den Kunden zur Abnahme der Webseite auffordern.</p>
              <p className="mb-4">2.1.6 Voraussetzung f&uuml;r die T&auml;tigkeit des Auftragnehmers ist, dass s&auml;mtliche vom Kunden zu stellenden und f&uuml;r die Umsetzung des Projekts erforderlichen Daten (z.&nbsp;B. Texte, Vorlagen, Grafiken, Schriften) und/oder Systemumgebungen dem Auftragnehmer rechtzeitig und in geeigneter Form zur Verf&uuml;gung gestellt werden. F&uuml;r Verz&ouml;gerungen und Versp&auml;tungen bei der Umsetzung von Projekten, die durch eine versp&auml;tete (notwendige) Mit- bzw. Zuarbeit des Kunden entstehen, ist der Auftragnehmer gegen&uuml;ber dem Kunden in keinerlei Hinsicht verantwortlich.</p>
              <p className="mb-4">2.1.7 Die Pr&uuml;fung oder Beschaffung von Rechten, die Beschaffung und/oder Einbindung von Plugins und/oder Tools (z.&nbsp;B. Statistik) oder Zertifikaten (z.&nbsp;B. SSL/TLS) sind vom Auftragnehmer nur dann geschuldet, soweit dies individualvertraglich ausdr&uuml;cklich vereinbart ist. Ein Anspruch auf die Herausgabe von Grafiken, Quellcodes, (Entwicklungs-)Dokumentationen, Handb&uuml;chern und sonstiger Zusatzdokumentation besteht – vorbehaltlich abweichender ausdr&uuml;cklicher Individualvereinbarungen – nicht.</p>
              <p className="mb-4">2.1.8 Soweit nicht anders vereinbart, sind die erstellten Webseiten f&uuml;r die Browser Chrome, Safari, Firefox und Edge in ihrer jeweils aktuellen Fassung optimiert (jeweils die letzten zwei Versionen des Browsers). Suchmaschinenoptimierung (SEO) wird nur geschuldet, wenn sie ausdr&uuml;cklich vereinbart wurde.</p>
              <p className="mb-4">2.1.9 Der Auftragnehmer ist nicht berechtigt und nicht verpflichtet, den Kunden zu wettbewerbs-, verbraucher-, kennzeichnungs- oder sonstigen rechtlichen Fragen im Sinne des Rechtsdienstleistungsgesetzes zu beraten. Es obliegt daher dem Kunden, sich &uuml;ber die f&uuml;r seinen Shop geltenden wettbewerbs-, verbraucher- oder kennzeichnungsrechtlichen Bestimmungen zu informieren und den Shop gegebenenfalls durch einen spezialisierten Rechtsanwalt pr&uuml;fen zu lassen.</p>
              <p className="mb-6">2.1.10 Nach Fertigstellung der Webseiten und/oder einzelner Teile hiervon kann der Auftragnehmer dem Kunden Wartungs- und Pflegeleistungen in Bezug auf die Webseiten anbieten. Jedoch ist weder der Auftragnehmer zu einem solchen Angebot verpflichtet, noch muss der Kunde die weitergehenden Leistungsangebote des Auftragnehmers in Anspruch nehmen. Entsprechende Vereinbarungen sind ausschlie&szlig;lich Gegenstand von Individualvereinbarungen. Werden keine zus&auml;tzlichen Wartungs- und Pflegeleistungen zwischen den Parteien vereinbart, ist nach Abnahme allein der Kunde f&uuml;r die technische Instandhaltung und Aktualit&auml;t der Webseiten verantwortlich. Der Auftragnehmer haftet gegen&uuml;ber dem Kunden nicht f&uuml;r eventuelle Sicherheitsl&uuml;cken, die durch die Verwendung veralteter Software von Dritten zu rechtswidrigen Zwecken ausgenutzt werden (Hacking).</p>

              <h3 className="text-xl font-semibold text-white mb-3">2.2 Webseiten- und Shoperstellung (Lasten- und Pflichtenheft)</h3>
              <p className="mb-4">2.2.1 Sofern zwischen den Vertragsparteien die Erstellung von neuen oder die Erweiterung bestehender Webseiten/Shops oder Web-/Shopkomponenten (nachfolgend „Webseitenerstellung") auf Grundlage eines Lasten- und Pflichtenhefts vereinbart wurde, erfolgt die Auftragsabwicklung nach Ma&szlig;gabe der vorliegenden Ziffer.</p>
              <p className="mb-4">2.2.2 Gegenstand von Webseiten-Erstellungsvertr&auml;gen zwischen dem Auftragnehmer und dem Kunden ist grunds&auml;tzlich die Entwicklung neuer Webseiten oder die Erweiterung bestehender Webseiten (z.&nbsp;B. Einbinden neuer Schnittstellen oder Programmierung neuer Online-Anwendungen) unter Beachtung der technischen und/oder gestalterischen Vorgaben des Kunden. Zwischen den Parteien geschlossene Webseiten-Erstellungsvertr&auml;ge sind Werkvertr&auml;ge im Sinne von §&sect; 631 ff. BGB.</p>
              <p className="mb-4">2.2.3 Ma&szlig;geblich f&uuml;r den Umfang der vom Auftragnehmer zu erbringenden Leistungen sind zum einen individualvertragliche Vereinbarungen zwischen den Parteien und zum anderen ein vom Kunden erstelltes, ausf&uuml;hrliches Lastenheft, sowie das darauf aufbauende Pflichtenheft. Der Auftragnehmer wird die im Lastenheft beschriebenen Vorstellungen des Kunden nach bestem Wissen und Gewissen auf Vollst&auml;ndigkeit, Eignung (mit Ausnahme der rechtlichen Eignung, insbesondere hinsichtlich der Rechte von Dritten), Eindeutigkeit, Realisierbarkeit und Widerspruchsfreiheit pr&uuml;fen. Sollte der Auftragnehmer erkennen, dass sich die im Lastenheft enthaltenen Vorgaben nicht f&uuml;r die Erstellung einer Webseite eignen, wird der Auftragnehmer den Kunden unverz&uuml;glich darauf hinweisen und einen entsprechenden Vorschlag f&uuml;r eine Erg&auml;nzung und/oder Anpassung des Lastenhefts unterbreiten. Der Kunde hat zu eventuellen Vorschl&auml;gen des Auftragnehmers hinsichtlich des Lastenhefts innerhalb eines angemessenen Zeitraums schriftlich oder in Textform Stellung zu nehmen und schlie&szlig;lich die Inhalte des Lastenhefts gegen&uuml;ber dem Auftragnehmer verbindlich schriftlich oder in Textform zu best&auml;tigen. Besteht zwischen den Parteien hinsichtlich des Lastenhefts Einigkeit, werden dessen Inhalte Vertragsbestandteil.</p>
              <p className="mb-4">2.2.4 Auf Grundlage des Lastenhefts erstellt der Auftragnehmer ein Pflichtenheft, das prim&auml;r die fachlich-technische und/oder gestalterische Umsetzung der im Lastenheft enthaltenen Vorgaben beschreibt. Nach Fertigstellung legt der Auftragnehmer dem Kunden das Pflichtenheft zur Abnahme vor. Der Kunde ist berechtigt, das vom Auftragnehmer erstellte Pflichtenheft zur&uuml;ckzuweisen und &Auml;nderungs- bzw. Anpassungsw&uuml;nsche mitzuteilen. Der Auftragnehmer verpflichtet sich, unter Ber&uuml;cksichtigung der W&uuml;nsche des Kunden, maximal zwei Alternativvorschl&auml;ge vorzulegen. Ist der Kunde mit dem letzten Vorschlag des Auftragnehmers endg&uuml;ltig nicht einverstanden, kann er oder der Auftragnehmer das Vertragsverh&auml;ltnis – sofern gesetzlich m&ouml;glich – au&szlig;erordentlich k&uuml;ndigen bzw. vom Vertrag zur&uuml;cktreten. Die im Zusammenhang mit dem Lasten- und/oder Pflichtenheft entstandenen Honorare und/oder Aufwendungen des Auftragnehmers sind vom Kunden in diesem Fall angemessen zu verg&uuml;ten bzw. zu ersetzen.</p>
              <p className="mb-4">2.2.5 Wird das Pflichtenheft vom Kunden abgenommen, gelten die dort beschriebenen Leistungen als zwischen den Parteien endg&uuml;ltig vereinbart. Jegliche Abweichung von den Inhalten des durch den Kunden abgenommenen Pflichtenhefts bed&uuml;rfen einer ausdr&uuml;cklichen Individualvereinbarung zwischen den Parteien. Der Auftragnehmer erbringt keine &uuml;ber die im vom Kunden abgenommenen Pflichtenheft beschriebenen Leistungen hinaus. Ebenso erbringt der Auftragnehmer grunds&auml;tzlich keine Minderleistungen im Verh&auml;ltnis zu den im vom Kunden abgenommenen Pflichtenheft beschriebenen Leistungen. Nach Abnahme des Pflichtenhefts durch den Kunden entwickelt und programmiert der Auftragnehmer die Webseiten unter Beachtung der vereinbarten Vorgaben.</p>
              <p className="mb-4">2.2.6 Der Auftragnehmer stellt dem Kunden neben dem Pflichtenheft einen Zeit- und Arbeitsplan zur Verf&uuml;gung. Die Inhalte und Vorgaben dieses Zeit- und Arbeitsplans werden Vertragsbestandteil, sofern der Kunde nicht unverz&uuml;glich widerspricht. Der Auftragnehmer verpflichtet sich, dem Kunden die fertige Webseite oder Teile hiervon bis zum im Zeit- und Arbeitsplan genannten Enddatum auf einem geeigneten Datentr&auml;ger zu &uuml;bergeben und/oder per E-Mail zuzusenden und/oder auf einen vom Kunden vorgegebenen Server hochzuladen. Die Einzelheiten der &Uuml;bergabe bzw. des Uploads der fertigen Webseiten sind im &Uuml;brigen Gegenstand individualvertraglicher Vereinbarungen zwischen den Parteien.</p>
              <p className="mb-4">2.2.7 Voraussetzung f&uuml;r die T&auml;tigkeit des Auftragnehmers ist, dass s&auml;mtliche vom Kunden zu stellenden und f&uuml;r die Umsetzung des Projekts erforderlichen Daten (z.&nbsp;B. Texte, Vorlagen, Grafiken) und/oder Systemumgebungen dem Auftragnehmer rechtzeitig und in geeigneter Form zur Verf&uuml;gung gestellt werden. F&uuml;r Verz&ouml;gerungen und Versp&auml;tungen bei der Umsetzung von Projekten, die durch eine versp&auml;tete (notwendige) Mit- bzw. Zuarbeit des Kunden entstehen, ist der Auftragnehmer gegen&uuml;ber dem Kunden in keinerlei Hinsicht verantwortlich.</p>
              <p className="mb-4">2.2.8 Sobald die Webseite fertiggestellt wurde, wird der Auftragnehmer den Kunden zur Abnahme der Webseite auffordern. Bei Bedarf kann vor der Abnahme eine Testphase vereinbart werden. Stellt der Kunde vor der Abnahme oder im Laufe einer vereinbarten Testphase Fehler fest, wird er diese gegen&uuml;ber dem Auftragnehmer schriftlich oder in Textform anzeigen. Der Auftragnehmer wird sich bem&uuml;hen, die Fehler fachgerecht zu korrigieren. Zu diesem Zwecke darf der Auftragnehmer vor&uuml;bergehende Workarounds bereitstellen.</p>
              <p className="mb-4">2.2.9 Die Pr&uuml;fung oder Beschaffung von Rechten, die Beschaffung und/oder Einbindung von Plugins und/oder Tools (z.&nbsp;B. Statistik) oder Zertifikaten (z.&nbsp;B. SSL/TLS) sind vom Auftragnehmer nur dann geschuldet, soweit dies individualvertraglich ausdr&uuml;cklich vereinbart ist. Ein Anspruch auf die Herausgabe von Grafiken, Quellcodes, (Entwicklungs-)Dokumentationen, Handb&uuml;chern und sonstiger Zusatzdokumentation besteht – vorbehaltlich abweichender ausdr&uuml;cklicher Individualvereinbarungen – nicht.</p>
              <p className="mb-4">2.2.10 Soweit nicht anders vereinbart sind die erstellten Webseiten f&uuml;r die Browser Chrome, Safari, Firefox und Edge in ihrer jeweils aktuellen Fassung optimiert (jeweils die letzten zwei Versionen des Browsers). Suchmaschinenoptimierung (SEO) wird nur geschuldet, wenn sie ausdr&uuml;cklich vereinbart wurde.</p>
              <p className="mb-4">2.2.11 Der Auftragnehmer ist nicht berechtigt und nicht verpflichtet, den Kunden zu wettbewerbs-, verbraucher-, kennzeichnungs- oder sonstigen rechtlichen Fragen im Sinne des Rechtsdienstleistungsgesetzes zu beraten. Es obliegt daher dem Kunden, sich &uuml;ber die f&uuml;r seinen Shop geltenden wettbewerbs-, verbraucher- oder kennzeichnungsrechtlichen Bestimmungen zu informieren und den Shop gegebenenfalls durch einen spezialisierten Rechtsanwalt pr&uuml;fen zu lassen.</p>
              <p className="mb-6">2.2.12 Nach Fertigstellung der Webseiten und/oder einzelner Teile hiervon kann der Auftragnehmer dem Kunden Wartungs- und Pflegeleistungen in Bezug auf die Webseiten anbieten. Jedoch ist weder der Auftragnehmer zu einem solchen Angebot verpflichtet, noch muss der Kunde die weitergehenden Leistungsangebote des Auftragnehmers in Anspruch nehmen. Entsprechende Vereinbarungen sind ausschlie&szlig;lich Gegenstand von Individualvereinbarungen. Werden keine zus&auml;tzlichen Wartungs- und Pflegeleistungen zwischen den Parteien vereinbart, ist nach Abnahme allein der Kunde f&uuml;r die technische Instandhaltung und Aktualit&auml;t der Webseiten verantwortlich. Der Auftragnehmer haftet gegen&uuml;ber dem Kunden nicht f&uuml;r eventuelle Sicherheitsl&uuml;cken, die durch die Verwendung veralteter Software von Dritten zu rechtswidrigen Zwecken ausgenutzt werden (Hacking).</p>

              <h3 className="text-xl font-semibold text-white mb-3">2.3 Wartung und Betreuung von Webseiten / Shops</h3>
              <p className="mb-4">2.3.1 Nach Fertigstellung der Webseiten und/oder einzelner Teile hiervon kann der Auftragnehmer dem Kunden Wartungs- und Betreuungsleistungen in Bezug auf die Webseiten anbieten (nachfolgend „Wartungsvertr&auml;ge"). Der Auftragnehmer kann auch die Wartung von Drittwebseiten anbieten. Jedoch ist weder der Auftragnehmer zu einem solchen Angebot verpflichtet, noch muss der Kunde die weitergehenden Leistungsangebote des Auftragnehmers in Anspruch nehmen. Entsprechende Vereinbarungen sind ausschlie&szlig;lich Gegenstand von Individualabsprachen.</p>
              <p className="mb-4">2.3.2 Inhalt der Wartungsvertr&auml;ge ist die Beseitigung von Funktionsst&ouml;rungen sowie die anlassbezogene Aktualisierung der Webseite f&uuml;r g&auml;ngige Webbrowser in ihrer jeweils aktuellen Version. Weitergehende Leistungen, wie z.&nbsp;B. regelm&auml;&szlig;ige Wartungen, k&ouml;nnen ggf. individualvertraglich vereinbart werden.</p>
              <p className="mb-4">2.3.3 Der Auftragnehmer haftet nicht f&uuml;r Funktionsst&ouml;rungen und Inkompatibilit&auml;ten, die durch eigenm&auml;chtige &Auml;nderungen des Kunden verursacht wurden oder auf sonstigen Fehlern beruhen, die nicht im Verantwortungsbereich des Auftragnehmers liegen; die Vorschriften unter „Haftung/Freistellung" bleiben hiervon unber&uuml;hrt.</p>
              <p className="mb-6">2.3.4 Die Wartung umfasst, vorbehaltlich abweichender Vereinbarungen, nur die technische, nicht jedoch die inhaltliche Aktualisierung der Webseite. Der Auftragnehmer schuldet vorbehaltlich abweichender Individualvereinbarungen insbesondere nicht die Aktualisierung des Impressums oder der Datenschutzerkl&auml;rung.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Teil 3 – Erstellung und Gestaltung von Content</h2>

              <h3 className="text-xl font-semibold text-white mb-3">3.1 Gestaltung von Printprodukten</h3>
              <p className="mb-4">3.1.1 Gegenstand von Designvertr&auml;gen im Printbereich zwischen dem Auftragnehmer und dem Kunden ist grunds&auml;tzlich die Entwicklung von Printprodukten nach den gestalterischen Vorgaben des Kunden (z.&nbsp;B. Ausgestaltung von Bannern, Postgrafiken, Plakaten, Schildern, Flyern, Roll-Ups, KFZ- oder Schaufenster-Beklebungen, Textilien oder Logo-Entw&uuml;rfen). Zwischen den Parteien geschlossene Designvertr&auml;ge sind Werkvertr&auml;ge im Sinne von § 631 ff. BGB.</p>
              <p className="mb-4">3.1.2 Die im Einzelnen vereinbarten Leistungen ergeben sich aus dem zwischen dem Auftragnehmer und dem Kunden individuell geschlossenen Vertrag. Hierzu stellt der Kunde beim Auftragnehmer zun&auml;chst eine Anfrage mit einer m&ouml;glichst genauen Beschreibung der von ihm gew&uuml;nschten Leistungen. Diese Anfrage stellt eine Aufforderung zur Abgabe eines Angebots durch Auftragnehmer dar. Der Auftragnehmer wird die in der Anfrage beschriebenen Vorstellungen des Kunden nach bestem Wissen und Gewissen auf Vollst&auml;ndigkeit, Eignung (mit Ausnahme der rechtlichen Eignung, insbesondere in Bezug auf die Rechte von Dritten), Eindeutigkeit, Realisierbarkeit und Widerspruchsfreiheit pr&uuml;fen und auf Grundlage der aus der Kundenanfrage hervorgehenden W&uuml;nsche ein Angebot erstellen. Erst durch die Annahme des Angebots durch den Kunden kommt ein Vertrag zwischen dem Auftragnehmer und dem Kunden zustande.</p>
              <p className="mb-4">3.1.3 Nach Abschluss des Vertrags werden die Anforderungen des Kunden bei Bedarf in einem weiteren Briefing besprochen und die Vorgaben konkretisiert. Zu diesem Zeitpunkt k&ouml;nnen Kundenw&uuml;nsche eingebracht werden, sofern diese durch den urspr&uuml;nglich vereinbarten Leistungsumfang gedeckt sind. Sofern erforderlich, besteht die M&ouml;glichkeit eines Rebriefings vor Fertigung des Leistungsgegenstands. Anpassungen werden Bestandteil des urspr&uuml;nglichen Vertrags, wenn beide Vertragsparteien in Textform (z.&nbsp;B. per E-Mail) zustimmen. Im &Uuml;brigen ist der Auftragnehmer nur zur Herstellung der im Vertrag aufgelisteten Positionen verpflichtet. Dar&uuml;berhinausgehende Leistungen m&uuml;ssen gesondert vereinbart und verg&uuml;tet werden.</p>
              <p className="mb-4">3.1.4 Soweit nichts anderes vereinbart, steht dem Kunden das Recht auf zwei Korrekturschleifen zu. Reklamationen hinsichtlich der k&uuml;nstlerischen Gestaltung sind nach Durchf&uuml;hrung der vereinbarten Korrekturschleifen grunds&auml;tzlich ausgeschlossen. W&uuml;nscht der Kunde dar&uuml;ber hinaus weitere &Auml;nderungen, so hat er die Mehrkosten zu tragen.</p>
              <p className="mb-4">3.1.5 Voraussetzung f&uuml;r die T&auml;tigkeit des Auftragnehmers ist, dass der Kunde s&auml;mtliche f&uuml;r die Umsetzung des Projekts erforderlichen Daten (Texte, Vorlagen, Grafiken etc.) dem Auftragnehmer vor Auftragsbeginn vollst&auml;ndig und in geeigneter Form zur Verf&uuml;gung stellt. F&uuml;r Verz&ouml;gerungen und Versp&auml;tungen bei der Umsetzung von Projekten, die durch eine versp&auml;tete (notwendige) Mit- bzw. Zuarbeit des Kunden entstehen, ist der Auftragnehmer gegen&uuml;ber dem Kunden in keinerlei Hinsicht verantwortlich. Kommt der Kunde dieser Verpflichtung nicht nach, kann der Auftragnehmer dem Kunden den hierdurch entstehenden Zeitaufwand in Rechnung stellen.</p>
              <p className="mb-6">3.1.6 Soweit vertraglich nicht anders vereinbart und vom Vertragszweck nicht anders zu erwarten, schuldet Auftragnehmer bei der Erstellung von Printprodukten neben den vertraglich vereinbarten Leistungsgegenst&auml;nden nur die &Uuml;bergabe einer g&auml;ngigen Druckdatei (z.&nbsp;B. PDF, JPG oder PNG). Der Kunde hat keinen Anspruch auf Herausgabe einer bearbeitbaren Datei (z.&nbsp;B. offene Dateien aus Grafikprogrammen).</p>

              <h3 className="text-xl font-semibold text-white mb-3">3.2 Erstellung von Texten / Copywriting</h3>
              <p className="mb-4">3.2.1 Der Auftragnehmer erstellt f&uuml;r den Kunden u.&nbsp;a. Texte (z.&nbsp;B. Pressemeldungen, Beitr&auml;ge f&uuml;r Webseiten, Werbetexte etc.). Die Inhalte dieser Texte werden individualvertraglich festgelegt.</p>
              <p className="mb-4">3.2.2 Sobald die vereinbarten Texte fertiggestellt wurden, wird der Auftragnehmer diese dem Kunden zur Freigabe und Abnahme &uuml;bermitteln. Soweit nicht anders vereinbart, steht dem Kunden das Recht auf zwei Korrekturschleifen zu. Reklamationen hinsichtlich der stilistischen Gestaltung oder die Einbindung neuer Informationen in den Text sind nach der zweiten &Auml;nderungsschleife grunds&auml;tzlich ausgeschlossen. W&uuml;nscht der Kunde dar&uuml;ber hinaus weitere &Auml;nderungen, so hat er die Mehrkosten zu tragen.</p>
              <p className="mb-4">3.2.3 Sofern der Auftragnehmer mit der Ver&ouml;ffentlichung beauftragt wurde, erfolgt die Ver&ouml;ffentlichung der Texte vorbehaltlich abweichender Vereinbarungen erst nach Freigabe durch den Kunden; die Freigabe stellt zugleich die Abnahme der Texte dar. Bei Pressemeldungen wird nach erfolgter Freigabe ferner ein Distributionsdatum festgelegt, an dem diese an die Medien &uuml;bermittelt werden sollen. Sofern der Kunde die Texte selbst ver&ouml;ffentlicht oder ver&ouml;ffentlichen soll, hat er die Texte vorab abzunehmen. Sofern der Kunde die Texte vor Abnahme ver&ouml;ffentlicht, gilt die Ver&ouml;ffentlichung als Abnahme.</p>
              <p className="mb-6">3.2.4 F&uuml;r Fehler, die nach der Freigabe/Abnahme entdeckt werden, haftet der Auftragnehmer ausschlie&szlig;lich nach Ma&szlig;gabe der Vorschriften unter der &Uuml;berschrift „Haftung/Freistellung".</p>

              <h3 className="text-xl font-semibold text-white mb-3">3.3 Gestaltung und Konzeption von Grafiken und Logos (Designs)</h3>
              <p className="mb-4">3.3.1 Der Auftragnehmer &uuml;bernimmt nach Vereinbarung mit dem Kunden die Konzeption und Gestaltung von Grafiken und/oder Logos (im Folgenden „Designs").</p>
              <p className="mb-4">3.3.2 Hierzu stellt der Kunde beim Auftragnehmer zun&auml;chst eine Anfrage mit einer m&ouml;glichst genauen Beschreibung der von ihm gew&uuml;nschten Designs. Diese Anfrage stellt eine Aufforderung zur Abgabe eines Angebots durch den Auftragnehmer dar. Der Auftragnehmer wird die in der Anfrage beschriebenen Vorstellungen des Kunden nach bestem Wissen und Gewissen auf Vollst&auml;ndigkeit, Eignung (mit Ausnahme der rechtlichen Eignung, insbesondere hinsichtlich der Rechte von Dritten), Eindeutigkeit, Realisierbarkeit und Widerspruchsfreiheit pr&uuml;fen und auf Grundlage der aus der Kundenanfrage hervorgehenden W&uuml;nsche ein Angebot erstellen. Erst durch die Annahme des Angebots durch den Kunden kommt ein Vertrag zwischen dem Auftragnehmer und dem Kunden zustande.</p>
              <p className="mb-4">3.3.3 Voraussetzung f&uuml;r die T&auml;tigkeit des Auftragnehmers ist, dass der Kunde s&auml;mtliche f&uuml;r die Umsetzung des Projekts erforderlichen Daten (Farbdefinition etc.) dem Auftragnehmer vor Auftragsbeginn vollst&auml;ndig in geeigneter Form zur Verf&uuml;gung stellt. Kommt der Kunde dieser Verpflichtung nicht nach, kann der Auftragnehmer dem Kunden den hierdurch entstehenden Zeitaufwand in Rechnung stellen.</p>
              <p className="mb-4">3.3.4 Soweit nichts anderes vereinbart, steht dem Kunden, die einzelnen Designs betreffend, das Recht auf je zwei Korrekturschleifen zu. Nach der Durchf&uuml;hrung dieser Korrekturschleifen werden Anpassungsw&uuml;nsche und Reklamationen (insbesondere hinsichtlich der k&uuml;nstlerischen Gestaltung) nicht mehr ber&uuml;cksichtigt. W&uuml;nscht der Kunde nach Durchf&uuml;hrung der vereinbarten Korrekturschleifen weitere &Auml;nderungen, kann der Auftragnehmer dem Kunden diese gegen ein zus&auml;tzlich zu vereinbarendes Entgelt erstellen.</p>
              <p className="mb-4">3.3.5 Sobald das vereinbarte Design fertiggestellt wurde, wird der Auftragnehmer den Kunden zur Abnahme des Werks auffordern. Die Designs werden dem Kunden in einem g&auml;ngigen Dateiformat zugesandt.</p>
              <p className="mb-4">3.3.6 Der Auftragnehmer r&auml;umt dem Kunden die f&uuml;r den jeweiligen Zweck erforderlichen Nutzungsrechte an den Designs ein. Vorbehaltlich abweichender Regelungen wird bei der Erstellung von Logos ein zeitlich, &ouml;rtlich und inhaltlich unbeschr&auml;nktes, ausschlie&szlig;liches Nutzungsrecht einger&auml;umt; einzelne grafische Elemente der Logos d&uuml;rfen jedoch f&uuml;r die Erstellung anderer Werke verwendet werden, solange hierdurch keine Verwechslungsgefahr zum erstellten Logo entsteht. Bei allen &uuml;brigen Designs wird vorbehaltlich abweichender Individualvereinbarungen ein einfaches Nutzungsrecht einger&auml;umt. Eine &Uuml;bertragung der Nutzungsrechte durch den Kunden an Dritte bedarf einer individualvertraglichen Vereinbarung mit dem Auftragnehmer. Die innerhalb der Korrekturschleife pr&auml;sentierten Entw&uuml;rfe d&uuml;rfen ohne ausdr&uuml;ckliche Einwilligung vom Auftragnehmer durch den Kunden weder im Original noch ver&auml;ndert genutzt, vervielf&auml;ltigt oder an Dritte weitergegeben werden.</p>
              <p className="mb-6">3.3.7 Die Nutzungsrechte gehen erst nach vollst&auml;ndiger Bezahlung der Verg&uuml;tung auf den Kunden &uuml;ber.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Teil 4 – Marketing</h2>

              <h3 className="text-xl font-semibold text-white mb-3">4.1 SEO-Marketing</h3>
              <p className="mb-6">Der Auftragnehmer bietet dem Kunden u.&nbsp;A. Dienstleistungen im Bereich SEO-Marketing an. Im Rahmen der Leistungserbringung schuldet der Auftragnehmer ausschlie&szlig;lich die Durchf&uuml;hrung von Ma&szlig;nahmen, die nach eigener Erfahrung des Auftragnehmers das Suchmaschinen-Ranking positiv beeinflussen k&ouml;nnen oder vom Kunden ausdr&uuml;cklich angeordnet werden. Hierbei handelt es sich um eine Dienstleistung im Sinne von §&sect; 611 ff. BGB. Ein bestimmtes Ergebnis (z.&nbsp;B. ein bestimmtes Ranking in der Suchmaschinen-Trefferliste) wird im Rahmen der SEO-Dienstleistungen dagegen nur dann geschuldet, wenn dieses ausdr&uuml;cklich zugesichert wurde.</p>

              <h3 className="text-xl font-semibold text-white mb-3">4.2 SEA-Kampagnen</h3>
              <p className="mb-6">Der Auftragnehmer bietet dem Kunden Dienstleistungen im Bereich von SEA-Kampagnen an. Im Rahmen der Leistungserbringung schuldet der Auftragnehmer ausschlie&szlig;lich die Unterbreitung von Vorschl&auml;gen bzgl. werbewirksamer Keywords und nach Freigabe des Kunden die Durchf&uuml;hrung der Ma&szlig;nahme (Schaltung von Werbeanzeigen). Hierbei handelt es sich um Dienstleistungen im Sinne von §&sect; 611 ff. BGB. Ein bestimmtes Ergebnis (z.&nbsp;B. Verkaufszahlen) wird im Rahmen von SEA-Dienstleistungen nicht geschuldet, es sei denn, dies wurde ausdr&uuml;cklich zugesichert. Den Auftragnehmer trifft nicht die Verpflichtung, die Rechtm&auml;&szlig;igkeit von Keywords zu &uuml;berpr&uuml;fen. Der Auftragnehmer unterbreitet dem Kunden Vorschl&auml;ge bzgl. der Buchung von Keywords. Die rechtliche Pr&uuml;fung, insbesondere auf die Markenrechte Dritter und Freigabe der Keywords, obliegt dem Kunden vor Durchf&uuml;hrung der Kampagne. Das f&uuml;r die vorliegend beschriebenen Leistungen vereinbarte Honorar beinhaltet nicht die Kosten f&uuml;r die Schaltung kostenpflichtiger Werbeanzeigen; vorbehaltlich abweichender Vereinbarungen sind diese Kosten vom Kunden zu tragen.</p>

              <h3 className="text-xl font-semibold text-white mb-3">4.3 Schaltung von Werbeanzeigen</h3>
              <p className="mb-4">4.3.1 Der Auftragnehmer unterst&uuml;tzt den Kunden bei Anzeigenschaltungen in Social-Media-Portalen, Suchmaschinen und sonstigen Medien („Anzeigen").</p>
              <p className="mb-4">4.3.2 Der Auftragnehmer ber&auml;t den Kunden dahingehend, wie dieser seine Anzeigen so ausgestaltet, dass diese eine m&ouml;glichst hohe Sichtbarkeit aufweisen. Bestimmte Ergebnisse (z.&nbsp;B. Verkaufszahlen, Leads) sind hierbei nicht geschuldet.</p>
              <p className="mb-4">4.3.3 Der Auftragnehmer unterst&uuml;tzt den Kunden auch bei der Konzeptionierung der Texte und Bilder f&uuml;r die Anzeigen. Die Auswahl der Inhalte f&uuml;r die Anzeigen (Bilder, Texte, Videos, Impressen etc.) obliegt jedoch allein dem Kunden. Der Auftragnehmer wird diese Inhalte, aber auch die Anzeigen insgesamt, nicht auf ihre inhaltliche oder rechtliche Richtigkeit pr&uuml;fen. Insoweit wird ausdr&uuml;cklich darauf hingewiesen, dass der Auftragnehmer nicht berechtigt ist, den Kunden rechtlich zu beraten. Sollte der Auftragnehmer in Einzelf&auml;llen dennoch feststellen, dass die vom Kunden bereitgestellten Inhalte und/oder die Anzeigen gegen geltendes Recht verstoßen, kann der Auftragnehmer das Einstellen solcher Inhalte bzw. Erstellen der Anzeigen verweigern.</p>
              <p className="mb-4">4.3.4 Alle Inhalte m&uuml;ssen vom Kunden abgenommen werden und werden hiernach vom Auftragnehmer in die jeweiligen Werbekan&auml;le hochgeladen, wobei der Auftragnehmer nur das technische Hochladen der Inhalte schuldet und auch nur hierf&uuml;r verantwortlich ist; die Regelungen unter „Haftung/Freistellung" bleiben unber&uuml;hrt.</p>
              <p className="mb-6">4.3.5 Das f&uuml;r die vorliegend beschriebenen Leistungen vereinbarte Honorar beinhaltet nicht die Kosten f&uuml;r die Schaltung kostenpflichtiger Werbeanzeigen; vorbehaltlich abweichender Vereinbarungen sind diese Kosten vom Kunden zu tragen.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-white mb-4">Teil 5 – Sonstige Bestimmungen</h2>

              <h3 className="text-xl font-semibold text-white mb-3">5.1 Preise und Verg&uuml;tung</h3>
              <p className="mb-6">Die Verg&uuml;tung f&uuml;r die Leistungen des Auftragnehmers ist Gegenstand einer individualvertraglichen Vereinbarung zwischen den Parteien und richtet sich grunds&auml;tzlich nach dem Angebot.</p>

              <h3 className="text-xl font-semibold text-white mb-3">5.2 Abnahme</h3>
              <p className="mb-6">Soweit eine Werkleistung vereinbart wurde, wird der Auftragnehmer den Kunden zur Abnahme auffordern. Die Abnahmefrist im Sinne des § 640 Abs.2 S.1 BGB wird auf 2 Wochen ab Abnahmeaufforderung festgelegt, sofern im Einzelfall aufgrund besonderer Umst&auml;nde nicht eine abweichende Abnahmefrist erforderlich ist, die der Auftragnehmer dem Kunden in diesem Fall gesondert mitteilen wird. Sofern sich der Kunde innerhalb dieser Frist nicht &auml;u&szlig;ert oder die Abnahme nicht wegen eines Mangels verweigert, gilt das Werk als abgenommen.</p>

              <h3 className="text-xl font-semibold text-white mb-3">5.3 M&auml;ngelgew&auml;hrleistung</h3>
              <p className="mb-6">Ein unwesentlicher Mangel begr&uuml;ndet keine M&auml;ngelanspr&uuml;che. Die Wahl der Art der Nacherf&uuml;llung liegt beim Auftragnehmer. Die Verj&auml;hrungsfrist f&uuml;r M&auml;ngel und sonstige Anspr&uuml;che betr&auml;gt ein (1) Jahr; diese Verj&auml;hrungsverk&uuml;rzung gilt nicht f&uuml;r Anspr&uuml;che, die aus Vorsatz, grober Fahrl&auml;ssigkeit oder aus der Verletzung von Leib, Leben oder Gesundheit durch den Auftragnehmer resultieren. Die Verj&auml;hrung beginnt nicht erneut, sofern im Rahmen der M&auml;ngelhaftung eine Nacherf&uuml;llung erfolgt. Im &Uuml;brigen bleibt die gesetzliche M&auml;ngelgew&auml;hrleistung unber&uuml;hrt.</p>

              <h3 className="text-xl font-semibold text-white mb-3">5.4 Rechteeinr&auml;umung, Eigenwerbung und Erw&auml;hnungsrecht</h3>
              <p className="mb-4">5.4.1 Der Auftragnehmer r&auml;umt dem Kunden – nach vollst&auml;ndiger Bezahlung des Auftrags durch den Kunden – an den entsprechenden Arbeitsergebnissen grunds&auml;tzlich ein einfaches, nicht &uuml;bertragbares Nutzungsrecht ein. Weitergehende Rechte k&ouml;nnen individualvertraglich vereinbart werden.</p>
              <p className="mb-4">5.4.2 Sofern nichts Abweichendes vereinbart wurde, erteilt der Kunde dem Auftragnehmer ausdr&uuml;cklich die Erlaubnis, das Projekt zum Zwecke der Eigenwerbung (Referenzen/Portfolio) in angemessener Weise &ouml;ffentlich darzustellen. Insbesondere ist der Auftragnehmer dazu berechtigt, mit der Gesch&auml;ftsbeziehung zu dem Kunden zu werben und auf allen erstellten Werbemitteln und bei allen Werbema&szlig;nahmen auf sich als Urheber hinzuweisen, ohne dass dem Kunden daf&uuml;r ein Entgeltanspruch zusteht.</p>
              <p className="mb-6">5.4.3 Ferner ist der Auftragnehmer berechtigt, den eigenen Namen, mit Verlinkung, in angemessener Weise im Footer und im Impressum der vom Auftragnehmer erstellten Webseite(n) zu platzieren, ohne dass dem Kunden hierf&uuml;r ein Entgeltanspruch zusteht.</p>

              <h3 className="text-xl font-semibold text-white mb-3">5.5 Vertraulichkeit</h3>
              <p className="mb-6">Der Auftragnehmer wird alle ihm zur Kenntnis gelangenden Gesch&auml;ftsvorg&auml;nge, insbesondere, aber nicht ausschlie&szlig;lich, Druckunterlagen, Layouts, Storyboards, Zahlenmaterial, Zeichnungen, Tonb&auml;nder, Bilder, Videos, DVDs, CD-ROMs, Speicherkarten, Passw&ouml;rter, interaktive Produkte und solche anderen Unterlagen, welche Filme und/oder H&ouml;rspiele und/oder sonstige urheberrechtlich gesch&uuml;tzte Materialien des Kunden oder mit ihm verbundenen Unternehmen enthalten, streng vertraulich behandeln. Der Auftragnehmer verpflichtet sich, die Geheimhaltungspflicht s&auml;mtlichen Angestellten und/oder Dritten (bspw. Lieferanten, Grafikern, Programmierern, Filmproduzenten, Tonstudios etc.), die Zugang zu den vorbezeichneten Gesch&auml;ftsvorg&auml;ngen haben, aufzuerlegen. Die Geheimhaltungspflicht gilt zeitlich unbegrenzt &uuml;ber die Dauer dieses Vertrages hinaus.</p>

              <h3 className="text-xl font-semibold text-white mb-3">5.6 Haftung/Freistellung</h3>
              <p className="mb-4">5.6.1 Der Auftragnehmer haftet aus jedem Rechtsgrund uneingeschr&auml;nkt bei Vorsatz oder grober Fahrl&auml;ssigkeit, bei vors&auml;tzlicher oder fahrl&auml;ssiger Verletzung des Lebens, des K&ouml;rpers oder der Gesundheit, aufgrund eines Garantieversprechens, soweit diesbez&uuml;glich nichts anderes geregelt ist oder aufgrund zwingender Haftung, wie etwa nach dem Produkthaftungsgesetz. Verletzt der Auftragnehmer fahrl&auml;ssig eine wesentliche Vertragspflicht, ist die Haftung auf den vertragstypischen, vorhersehbaren Schaden begrenzt, sofern nicht gem&auml;&szlig; vorstehendem Satz unbeschr&auml;nkt gehaftet wird. Wesentliche Vertragspflichten sind Pflichten, die der Vertrag dem Auftragnehmer nach seinem Inhalt zur Erreichung des Vertragszwecks auferlegt, deren Erf&uuml;llung die ordnungsgem&auml;&szlig;e Durchf&uuml;hrung des Vertrags &uuml;berhaupt erst erm&ouml;glicht und auf deren Einhaltung der Kunde regelm&auml;&szlig;ig vertrauen darf. Im &Uuml;brigen ist eine Haftung des Auftragnehmers ausgeschlossen. Vorstehende Haftungsregelungen gelten auch im Hinblick auf die Haftung des Auftragnehmers f&uuml;r seine Erf&uuml;llungsgehilfen und gesetzlichen Vertreter.</p>
              <p className="mb-6">5.6.2 Der Kunde stellt den Auftragnehmer von jeglichen Anspr&uuml;chen Dritter frei, die gegen den Auftragnehmer aufgrund von Verst&ouml;&szlig;en des Kunden gegen diese AGB oder gegen geltendes Recht geltend gemacht werden.</p>

              <h3 className="text-xl font-semibold text-white mb-3">5.7 Schlussbestimmungen</h3>
              <p className="mb-4">5.7.1 Die zwischen dem Auftragnehmer und den Kunden geschlossenen Vertr&auml;ge unterliegen dem materiellen Recht der Bundesrepublik Deutschland unter Ausschluss des UN-Kaufrechts.</p>
              <p className="mb-4">5.7.2 Sofern der Kunde Kaufmann, juristische Person des &ouml;ffentlichen Rechts oder &ouml;ffentlich-rechtliches Sonderverm&ouml;gen ist oder keinen allgemeinen Gerichtsstand in Deutschland hat, vereinbaren die Parteien den Sitz des Auftragnehmers als Gerichtsstand f&uuml;r s&auml;mtliche Streitigkeiten aus diesem Vertragsverh&auml;ltnis; ausschlie&szlig;liche Gerichtsst&auml;nde bleiben hiervon unber&uuml;hrt.</p>
              <p className="mb-6">5.7.3 Der Auftragnehmer ist berechtigt, diese AGB aus sachlich gerechtfertigten Gr&uuml;nden (z.&nbsp;B. &Auml;nderungen in der Rechtsprechung, Gesetzeslage, Marktgegebenheiten oder der Gesch&auml;fts- oder Unternehmensstrategie) und unter Einhaltung einer angemessenen Frist zu &auml;ndern. Bestandskunden werden hier&uuml;ber sp&auml;testens zwei Wochen vor Inkrafttreten der &Auml;nderung per E-Mail benachrichtigt. Sofern der Bestandskunde nicht innerhalb der in der &Auml;nderungsmitteilung gesetzten Frist widerspricht, gilt seine Zustimmung zur &Auml;nderung als erteilt. Widerspricht er, treten die &Auml;nderungen nicht in Kraft; der Auftragnehmer ist in diesem Fall berechtigt, den Vertrag zum Zeitpunkt des Inkrafttretens der &Auml;nderung au&szlig;erordentlich zu k&uuml;ndigen. Die Benachrichtigung &uuml;ber die beabsichtigte &Auml;nderung dieser AGB wird auf die Frist und die Folgen des Widerspruchs oder seines Ausbleibens hinweisen.</p>
            </section>
          </div>

          <div className="mt-10 pt-6 border-t border-white/10">
            <Link href="/" className="text-[#ff5500] hover:underline">
              Zurück zur Startseite
            </Link>
          </div>
        </div>
      </div>
      <Footer />
    </main>
  );
} 